In [1]:
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
house_dataFrame = pd.read_csv('https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv')

In [4]:
house_dataFrame.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [5]:
house_dataFrame.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [6]:
house_dataFrame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
longitude,17000.0,-119.562108,2.005166,-124.3500,-121.790000,-118.4900,-118.000,-114.3100
latitude,17000.0,35.625225,2.137340,32.5400,33.930000,34.2500,37.720,41.9500
housing_median_age,17000.0,28.589353,12.586937,1.0000,18.000000,29.0000,37.000,52.0000
total_rooms,17000.0,2643.664412,2179.947071,2.0000,1462.000000,2127.0000,3151.250,37937.0000
total_bedrooms,17000.0,539.410824,421.499452,1.0000,297.000000,434.0000,648.250,6445.0000
population,17000.0,1429.573941,1147.852959,3.0000,790.000000,1167.0000,1721.000,35682.0000
households,17000.0,501.221941,384.520841,1.0000,282.000000,409.0000,605.250,6082.0000
median_income,17000.0,3.883578,1.908157,0.4999,2.566375,3.5446,4.767,15.0001
median_house_value,17000.0,207300.912353,115983.764387,14999.0000,119400.000000,180400.0000,265000.000,500001.0000

In [7]:
x_data = house_dataFrame.drop(['median_house_value'],axis=1)

In [8]:
y_val = house_dataFrame['median_house_value']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler = MinMaxScaler()

In [12]:
x_data = pd.DataFrame(data=scaler.fit_transform(x_data),
                      columns=x_data.columns,
                      index=x_data.index)

In [13]:
x_data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,0.476882,0.327867,0.540968,0.069637,0.083552,0.039984,0.082260,0.233354
std,0.199718,0.227135,0.246803,0.057465,0.065410,0.032172,0.063233,0.131595
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.254980,0.147715,0.333333,0.038487,0.045934,0.022058,0.046210,0.142514
50%,0.583665,0.181722,0.549020,0.056017,0.067194,0.032624,0.067094,0.209976
75%,0.632470,0.550478,0.705882,0.083017,0.100442,0.048152,0.099367,0.294279
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3, random_state=101)
#I usually prefer random_state as 101, anyone pick any number as you wish.

In [15]:
x_data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [16]:
age = tf.feature_column.numeric_column('housing_median_age')
rooms = tf.feature_column.numeric_column('total_rooms')
bedrooms = tf.feature_column.numeric_column('total_bedrooms')
pop = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
income = tf.feature_column.numeric_column('median_income')
long = tf.feature_column.numeric_column('longitude')
latit = tf.feature_column.numeric_column('latitude')

In [17]:
#bucketized columns added to model
buc_long = tf.feature_column.bucketized_column(source_column=long, boundaries=[0.2,0.4,0.6,0.8])
buc_latit = tf.feature_column.bucketized_column(source_column=latit,boundaries=[0.2,0.4,0.6,0.8])

In [18]:
feat_cols = [age,rooms,bedrooms,pop,households,income,buc_long,buc_latit]

In [19]:
feat_cols

[_NumericColumn(key='housing_median_age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='total_rooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='total_bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='population', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='households', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='median_income', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _BucketizedColumn(source_column=_NumericColumn(key='longitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(0.2, 0.4, 0.6, 0.8)),
 _BucketizedColumn(source_column=_NumericColumn(key='latitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(0.2, 0.4, 0.6, 0.8))]

In [20]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,
                                                 y=y_train,
                                                 batch_size=10,
                                                 num_epochs=10000,
                                                 shuffle=True)

In [21]:
model = tf.estimator.DNNRegressor(hidden_units=[3,6,10],
                                  feature_columns=feat_cols)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/x_/4p6qzwq12gggwpj74t_g5pth0000gn/T/tmpbbdndk2y
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/x_/4p6qzwq12gggwpj74t_g5pth0000gn/T/tmpbbdndk2y', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a31a95c88>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [22]:
model.train(input_fn=input_func,steps=10000)

WARNING:tensorflow:From /Users/halilkacmaz/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /Users/halilkacmaz/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /Users/halilkacmaz/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/x_/4p6qzwq12gggwpj74t_g5pth0000gn/T/tmpbbdndk2y/model.ckpt.
INFO:tensorflow:loss = 515989540000.0, step = 1
INFO:tensorflow:global_step/sec: 404.544
INFO:tensorflow:loss = 454625600000.0, step = 101 (0.247 sec)
INFO:tensorflow:global_step/sec: 576.817
INFO:tensorflow:loss = 314484520000.0, step = 201 (0.173 sec)
INFO:tensorflow:global_step/sec: 559.923
INFO:tensorflow:loss = 432648260000.0, step = 301 (0.179 sec)
INFO:tensorflow:global_step/sec: 654.472
INFO:tensorflow:loss = 503137730000.0, step = 401 (0.153 sec)
INFO:tensorflow:global_step/sec: 545.339
INFO:tensorflow:loss = 583890440000.0, step = 501 (0.184 sec)
INFO:tensorflow:global_step/sec: 554.647
INFO:tensorflow:loss = 434746360000.0, step = 601 (0.180 sec)
INFO:tensorflow:global_step/sec: 566.592
INFO:tensorflow:loss = 91962770000.0, step = 701 (0.176 sec)
INFO:tensorflow:global_step/sec: 569.464
INFO:tensorflow:loss = 371248700000.0, step = 801 (0.176 sec)
INFO:tensorflow:global_step/sec: 580.137
INFO:tensorflow:loss = 165694230000.0, step = 901 (0.172 sec)
INFO:tensorflow:global_step/sec: 565.348
INFO:tensorflow:loss = 201518330000.0, step = 1001 (0.177 sec)
INFO:tensorflow:global_step/sec: 563.193
INFO:tensorflow:loss = 172499190000.0, step = 1101 (0.177 sec)
INFO:tensorflow:global_step/sec: 551.822
INFO:tensorflow:loss = 65631420000.0, step = 1201 (0.181 sec)
INFO:tensorflow:global_step/sec: 566.187
INFO:tensorflow:loss = 178313380000.0, step = 1301 (0.177 sec)
INFO:tensorflow:global_step/sec: 559.756
INFO:tensorflow:loss = 274545510000.0, step = 1401 (0.179 sec)
INFO:tensorflow:global_step/sec: 577.41
INFO:tensorflow:loss = 61507700000.0, step = 1501 (0.173 sec)
INFO:tensorflow:global_step/sec: 530.857
INFO:tensorflow:loss = 196370730000.0, step = 1601 (0.188 sec)
INFO:tensorflow:global_step/sec: 514.827
INFO:tensorflow:loss = 124568570000.0, step = 1701 (0.196 sec)
INFO:tensorflow:global_step/sec: 493.445
INFO:tensorflow:loss = 161428340000.0, step = 1801 (0.202 sec)
INFO:tensorflow:global_step/sec: 606.042
INFO:tensorflow:loss = 79420910000.0, step = 1901 (0.166 sec)
INFO:tensorflow:global_step/sec: 528.925
INFO:tensorflow:loss = 177952100000.0, step = 2001 (0.187 sec)
INFO:tensorflow:global_step/sec: 609.428
INFO:tensorflow:loss = 101699060000.0, step = 2101 (0.164 sec)
INFO:tensorflow:global_step/sec: 570.526
INFO:tensorflow:loss = 188910710000.0, step = 2201 (0.175 sec)
INFO:tensorflow:global_step/sec: 556.604
INFO:tensorflow:loss = 68543030000.0, step = 2301 (0.180 sec)
INFO:tensorflow:global_step/sec: 554.631
INFO:tensorflow:loss = 226703110000.0, step = 2401 (0.180 sec)
INFO:tensorflow:global_step/sec: 581.548
INFO:tensorflow:loss = 23546340000.0, step = 2501 (0.172 sec)
INFO:tensorflow:global_step/sec: 566.591
INFO:tensorflow:loss = 121321410000.0, step = 2601 (0.176 sec)
INFO:tensorflow:global_step/sec: 562.063
INFO:tensorflow:loss = 63961930000.0, step = 2701 (0.178 sec)
INFO:tensorflow:global_step/sec: 580.037
INFO:tensorflow:loss = 42155254000.0, step = 2801 (0.172 sec)
INFO:tensorflow:global_step/sec: 571.086
INFO:tensorflow:loss = 77583930000.0, step = 2901 (0.175 sec)
INFO:tensorflow:global_step/sec: 571.083
INFO:tensorflow:loss = 39531057000.0, step = 3001 (0.175 sec)
INFO:tensorflow:global_step/sec: 563.578
INFO:tensorflow:loss = 68917640000.0, step = 3101 (0.177 sec)
INFO:tensorflow:global_step/sec: 568.307
INFO:tensorflow:loss = 78230610000.0, step = 3201 (0.176 sec)
INFO:tensorflow:global_step/sec: 575.279
INFO:tensorflow:loss = 110935015000.0, step = 3301 (0.174 sec)
INFO:tensorflow:global_step/sec: 567.311
INFO:tensorflow:loss = 86305060000.0, step = 3401 (0.176 sec)
INFO:tensorflow:global_step/sec: 575.703
INFO:tensorflow:loss = 57127588000.0, step = 3501 (0.174 sec)
INFO:tensorflow:global_step/sec: 566.074
INFO:tensorflow:loss = 45295964000.0, step = 3601 (0.177 sec)
INFO:tensorflow:global_step/sec: 563.606
INFO:tensorflow:loss = 73265320000.0, step = 3701 (0.177 sec)
INFO:tensorflow:global_step/sec: 564.07
INFO:tensorflow:loss = 48138682000.0, step = 3801 (0.177 sec)
INFO:tensorflow:global_step/sec: 568.06
INFO:tensorflow:loss = 57182920000.0, step = 3901 (0.176 sec)
INFO:tensorflow:global_step/sec: 585.627
INFO:tensorflow:loss = 132154870000.0, step = 4001 (0.171 sec)
INFO:tensorflow:global_step/sec: 576.213
INFO:tensorflow:loss = 178184720000.0, step = 4101 (0.174 sec)
INFO:tensorflow:global_step/sec: 571.637
INFO:tensorflow:loss = 246325610000.0, step = 4201 (0.175 sec)
INFO:tensorflow:global_step/sec: 534.368
INFO:tensorflow:loss = 89856926000.0, step = 4301 (0.187 sec)
INFO:tensorflow:global_step/sec: 577.981
INFO:tensorflow:loss = 136425010000.0, step = 4401 (0.173 sec)
INFO:tensorflow:global_step/sec: 585.076
INFO:tensorflow:loss = 141669600000.0, step = 4501 (0.171 sec)
INFO:tensorflow:global_step/sec: 578.499
INFO:tensorflow:loss = 105625940000.0, step = 4601 (0.173 sec)
INFO:tensorflow:global_step/sec: 578.132
INFO:tensorflow:loss = 128991855000.0, step = 4701 (0.173 sec)
INFO:tensorflow:global_step/sec: 580.057
INFO:tensorflow:loss = 158022570000.0, step = 4801 (0.172 sec)
INFO:tensorflow:global_step/sec: 539.517
INFO:tensorflow:loss = 53407695000.0, step = 4901 (0.185 sec)
INFO:tensorflow:global_step/sec: 543.54
INFO:tensorflow:loss = 229956760000.0, step = 5001 (0.184 sec)
INFO:tensorflow:global_step/sec: 597.882
INFO:tensorflow:loss = 118310000000.0, step = 5101 (0.168 sec)
INFO:tensorflow:global_step/sec: 557.364
INFO:tensorflow:loss = 79486255000.0, step = 5201 (0.178 sec)
INFO:tensorflow:global_step/sec: 574.26
INFO:tensorflow:loss = 91234300000.0, step = 5301 (0.174 sec)
INFO:tensorflow:global_step/sec: 555.679
INFO:tensorflow:loss = 42243530000.0, step = 5401 (0.180 sec)
INFO:tensorflow:global_step/sec: 531.858
INFO:tensorflow:loss = 75292100000.0, step = 5501 (0.188 sec)
INFO:tensorflow:global_step/sec: 591.017
INFO:tensorflow:loss = 42082144000.0, step = 5601 (0.169 sec)
INFO:tensorflow:global_step/sec: 577.624
INFO:tensorflow:loss = 134206880000.0, step = 5701 (0.173 sec)
INFO:tensorflow:global_step/sec: 582.356
INFO:tensorflow:loss = 120122200000.0, step = 5801 (0.172 sec)
INFO:tensorflow:global_step/sec: 581.73
INFO:tensorflow:loss = 42093535000.0, step = 5901 (0.172 sec)
INFO:tensorflow:global_step/sec: 575.275
INFO:tensorflow:loss = 121810444000.0, step = 6001 (0.174 sec)
INFO:tensorflow:global_step/sec: 567.988
INFO:tensorflow:loss = 60632773000.0, step = 6101 (0.176 sec)
INFO:tensorflow:global_step/sec: 580.319
INFO:tensorflow:loss = 101586575000.0, step = 6201 (0.172 sec)
INFO:tensorflow:global_step/sec: 591.814
INFO:tensorflow:loss = 68568396000.0, step = 6301 (0.169 sec)
INFO:tensorflow:global_step/sec: 579.24
INFO:tensorflow:loss = 83164870000.0, step = 6401 (0.173 sec)
INFO:tensorflow:global_step/sec: 586.838
INFO:tensorflow:loss = 49994370000.0, step = 6501 (0.171 sec)

INFO:tensorflow:global_step/sec: 468.364
INFO:tensorflow:loss = 27535444000.0, step = 6601 (0.214 sec)
INFO:tensorflow:global_step/sec: 519.551
INFO:tensorflow:loss = 111311680000.0, step = 6701 (0.192 sec)
INFO:tensorflow:global_step/sec: 505.096
INFO:tensorflow:loss = 52778740000.0, step = 6801 (0.199 sec)
INFO:tensorflow:global_step/sec: 503.888
INFO:tensorflow:loss = 149582580000.0, step = 6901 (0.198 sec)
INFO:tensorflow:global_step/sec: 501.456
INFO:tensorflow:loss = 84773950000.0, step = 7001 (0.199 sec)
INFO:tensorflow:global_step/sec: 532.822
INFO:tensorflow:loss = 132667150000.0, step = 7101 (0.188 sec)
INFO:tensorflow:global_step/sec: 532.831
INFO:tensorflow:loss = 69116805000.0, step = 7201 (0.188 sec)
INFO:tensorflow:global_step/sec: 471.396
INFO:tensorflow:loss = 174161560000.0, step = 7301 (0.212 sec)
INFO:tensorflow:global_step/sec: 517.539
INFO:tensorflow:loss = 145544540000.0, step = 7401 (0.194 sec)
INFO:tensorflow:global_step/sec: 628.808
INFO:tensorflow:loss = 108429690000.0, step = 7501 (0.158 sec)
INFO:tensorflow:global_step/sec: 582.605
INFO:tensorflow:loss = 108074140000.0, step = 7601 (0.172 sec)
INFO:tensorflow:global_step/sec: 584.379
INFO:tensorflow:loss = 66330390000.0, step = 7701 (0.171 sec)
INFO:tensorflow:global_step/sec: 585.431
INFO:tensorflow:loss = 34477945000.0, step = 7801 (0.171 sec)
INFO:tensorflow:global_step/sec: 580.612
INFO:tensorflow:loss = 77154075000.0, step = 7901 (0.172 sec)
INFO:tensorflow:global_step/sec: 588.328
INFO:tensorflow:loss = 89044570000.0, step = 8001 (0.170 sec)
INFO:tensorflow:global_step/sec: 587.676
INFO:tensorflow:loss = 146150230000.0, step = 8101 (0.170 sec)
INFO:tensorflow:global_step/sec: 589.087
INFO:tensorflow:loss = 110117044000.0, step = 8201 (0.170 sec)
INFO:tensorflow:global_step/sec: 582.673
INFO:tensorflow:loss = 50037670000.0, step = 8301 (0.172 sec)
INFO:tensorflow:global_step/sec: 581.338
INFO:tensorflow:loss = 70168380000.0, step = 8401 (0.172 sec)
INFO:tensorflow:global_step/sec: 610.982
INFO:tensorflow:loss = 48624628000.0, step = 8501 (0.164 sec)
INFO:tensorflow:global_step/sec: 582.228
INFO:tensorflow:loss = 59119665000.0, step = 8601 (0.172 sec)
INFO:tensorflow:global_step/sec: 583.005
INFO:tensorflow:loss = 46350885000.0, step = 8701 (0.172 sec)
INFO:tensorflow:global_step/sec: 586.721
INFO:tensorflow:loss = 128941400000.0, step = 8801 (0.171 sec)
INFO:tensorflow:global_step/sec: 561.927
INFO:tensorflow:loss = 124652490000.0, step = 8901 (0.178 sec)
INFO:tensorflow:global_step/sec: 581.903
INFO:tensorflow:loss = 53650293000.0, step = 9001 (0.172 sec)
INFO:tensorflow:global_step/sec: 547.1
INFO:tensorflow:loss = 75268380000.0, step = 9101 (0.183 sec)
INFO:tensorflow:global_step/sec: 584.878
INFO:tensorflow:loss = 162728970000.0, step = 9201 (0.171 sec)
INFO:tensorflow:global_step/sec: 574.141
INFO:tensorflow:loss = 108428460000.0, step = 9301 (0.174 sec)
INFO:tensorflow:global_step/sec: 575.146
INFO:tensorflow:loss = 106778100000.0, step = 9401 (0.174 sec)
INFO:tensorflow:global_step/sec: 579.177
INFO:tensorflow:loss = 136713880000.0, step = 9501 (0.173 sec)
INFO:tensorflow:global_step/sec: 578.466
INFO:tensorflow:loss = 78485060000.0, step = 9601 (0.173 sec)
INFO:tensorflow:global_step/sec: 573.132
INFO:tensorflow:loss = 108252360000.0, step = 9701 (0.174 sec)
INFO:tensorflow:global_step/sec: 585.134
INFO:tensorflow:loss = 118762590000.0, step = 9801 (0.171 sec)
INFO:tensorflow:global_step/sec: 587.289
INFO:tensorflow:loss = 86704510000.0, step = 9901 (0.170 sec)
INFO:tensorflow:Saving checkpoints for 10000 into /var/folders/x_/4p6qzwq12gggwpj74t_g5pth0000gn/T/tmpbbdndk2y/model.ckpt.
INFO:tensorflow:Loss for final step: 139358540000.0.

In [23]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test,
                                                         batch_size=10,
                                                         num_epochs=1,
                                                         shuffle=False)

In [24]:
pred_gen = model.predict(predict_input_func)

In [25]:
predictions = list(pred_gen)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/x_/4p6qzwq12gggwpj74t_g5pth0000gn/T/tmpbbdndk2y/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [26]:
final_preds=[]
for pred in predictions:
    final_preds.append(pred['predictions'])

In [27]:
from sklearn.metrics import mean_squared_error

In [28]:
mean_squared_error(y_test,final_preds)**0.5

101139.70797537142